### ISSUE TITLE
[BUG] PluginContainer not found

### ISSUE THREAD

**Issue by Lorenzo0111** [Fernthedev/FernAPI#101]
**Describe the bug**
When I start the server it says an error

**Stacktrace**
[The error stacktrace](https://paste.helpch.at/yibexipaka.sql)

**Code**
[Here](https://paste.helpch.at/olulivopay.java)

**To Reproduce**
1. Start the server

**Expected behavior**
No error

**Platform (please complete the following information):**
 - OS: Ubuntu
 - ServerPlatform: Velocity 3.0.0

**Comment by Fernthedev** [comment]
This is not my plugin?

**Comment by Fernthedev** [comment]
Wait nevermind the stacktrace just didn't show anything FernAPI related 🤔

**Comment by Fernthedev** [comment]
Please attempt to use [this version](https://jitpack.io/#Fernthedev/FernAPI/3f99cc5c7f) rather than the releases as they're extremely outdated.

**Comment by Lorenzo0111** [comment]
> 
> 
> Wait nevermind the stacktrace just didn't show anything FernAPI related 🤔

that exception was caused by the api but you already fixed it in 8a976479e188b653b8af179e2b5fb1c051f1172d
